### ISSUE TITLE
[Task] 회원정보 수정, 회원탈퇴 기능 추가  

### ISSUE THREAD

**Issue by haagmin5382** [codestates/MemoryRoad#121]
### ISSUE
- Group:  `client`
- Type: `bug`, `feature`
- Detail: 회원정보 수정 ,회원탈퇴 시 요구되는 API 요청 작성, CSS 반응형 디자인 수정  

### TODO
1. [x] 회원정보 수정 API요청 함수를 작성하고 서버와 통신
2. [x] 회원탈퇴 API요청 함수를 작성하고 서버와 통신
3. [x] CSS 반응형 디자인 수정

### Labels
- Estimated time: `E: 3h`
- Group : `client`
- Sprint: `Sprint__1`
- Urgency: `High`
