### ISSUE TITLE
[Task] 유저 CRUD 에러 핸들링 리팩토링

### ISSUE THREAD

**Issue by jyang510** [codestates/MemoryRoad#132]
### ISSUE
- Group:  `server`
- Type: `bug`, `feature`, `delete`
- Detail: nestJS에서 권장하는 Exception Filters를 이용하여, 에러 핸들링을 커스텀하여 단순히 res.status 전달을

### TODO
1. [x] users,service.ts 수정
2. [x] users.controller.ts 수정 
3. [x] users.filter 파일 생성하여 에러 핸들링하기
 
### Estimated time
> Pick one
### Labels
- Estimated time: `E: 3h`
- Group : `server`
- Sprint: `Sprint__1`
- Urgency: `middle`
