### ISSUE TITLE
[Task] 루트 생성 창, 루트 수정 창 버그 수정

### ISSUE THREAD

**Issue by ciocio97** [codestates/MemoryRoad#155]
### ISSUE
- Group:  `client`
- Type: `bug`, `delete`
- Detail: 루트 생성창 로직 변경, 상태 업데이트 버그 수정

### TODO
1. [x] 루트 삭제 시 스토리카드 위치가 변경되는 오류 수정
2. [x] 루트 순서 변경 시 지도 오작동 오류 수정
3. [x] react-grid-layout 속성 공부하기

### Labels
- Estimated time: `E: 3h`
- Group : `client`
- Sprint: `Sprint__NUMBER1`
- Urgency: `High`
