### ISSUE TITLE
[Task] 루트 수정창 구현, 서버 통신 테스트

### ISSUE THREAD

**Issue by ciocio97** [codestates/MemoryRoad#157]
### ISSUE
- Group:  `client`
- Type: `feature`
- Detail: 루트 수정창에서 수정, 삭제, 추가 기능을 구현합니다.

### TODO
1. [x] 기존 데이터 받아오는 axios 요청 구현
2. [x] 기존 데이터의 사진과 추가된 사진 구분하는 로직 구현
3. [x] 수정, 삭제 요청 시 axios 요청 구현

### Labels
- Estimated time: `E: 5h`
- Group : `client`
- Sprint: `Sprint__NUMBER1`
- Urgency: `High`
