### ISSUE TITLE
[Task] 핀 수정, 삭제 API구현

### ISSUE THREAD

**Issue by PippasSong** [codestates/MemoryRoad#17]
### ISSUE
- Group:  `server`
- Type: `feature`
- Detail: PATCH, DELETE /routes/{routeId}/pins/{pinId} 엔드포인트 구현

### TODO
1. [x] pin 카드 수정 기능 구현. 없는 pinId가 주어질 경우 pin을 새로 생성
2. [x] pin 카드 삭제 기능 구현
3. [x] API 문서 확인

### Labels
- Estimated time: `E: 5h`
- Group : `server`
- Sprint: `Sprint__1`
- Urgency: `Middle`
