### ISSUE TITLE
[Task] 네비게이션바 구현 

### ISSUE THREAD

**Issue by haagmin5382** [codestates/MemoryRoad#21]
### ISSUE
- Group:  `client`
- Type: `feature`
- Detail: 화면의 윗부분에 해당하는 네비게이션바 구현 (Nav Component) 

### TODO
1. [x] 네비게이션바의 디자인을 구현
2. [x] 태블릿이나 모바일로 접속했을 때 화면에 나오는 반응형 디자인 구현
3. [x] 메뉴버튼을 누르면 나오는 화면 구현

### Labels
- Estimated time: `E: 2h`
- Group : `client`
- Sprint: `Sprint__1`
- Urgency: `Middle`
