### ISSUE TITLE
[Task] 루트 보관함의 루트 카드 컴포넌트 구현

### ISSUE THREAD

**Issue by ciocio97** [codestates/MemoryRoad#22]
### ISSUE
- Group:  `client`
- Type: `feature`
- Detail: 루트보관함과 지도 검색페이지에서 사용되는 루트 카드 컴포넌트 구현

### TODO
1. [x] 루트 제목
2. [x] 루트의 날짜
3. [x] 루트 진행 시간
4. [x] 루트에 찍힌 장소의 제목
5. [x] 루트의 대표 사진

### Labels
- Estimated time: `E: 1.5h`
- Group : `client`
- Sprint: `Sprint__1`
- Urgency: `Low`
