### ISSUE TITLE
[Task] 루트 보관함 구조, 기능 구현

### ISSUE THREAD

**Issue by ciocio97** [codestates/MemoryRoad#24]
### ISSUE
- Group:  `client`
- Type: `structure`
- Detail: 루트 보관함 반응형 구조 & 기능 구현

### TODO
1. [x] `내 루트 보관함` 텍스트 섹션
2. [x] 루트 카드 필터링 창 3개 : 기준3가지 - 색 / 지역 / 검색어 (div박스 반으로 나눠 반응형 대응)
3. [x] 루트 카드 창 스크롤바 구현 & 디자인
4. [x] 루트 카드 추가 버튼 : 이벤트 핸들러 등록
5. [x] 루트 카드는 첫 화면에서 9개만 보여짐 -> 페이지네이션 구현

### Labels
- Estimated time: `E: 3h`
- Group : `client`
- Sprint: `Sprint__1`
- Urgency: `High`
