### ISSUE TITLE
[Task] 카카오 지도 API test

### ISSUE THREAD

**Issue by ciocio97** [codestates/MemoryRoad#26]
### ISSUE
- Group:  `client`
- Type: `study`
- Detail: 카카오 지도 API 테스트 렌더링

### TODO
1. [x] 지도에 여러개의 마커 표시하기
2. [x] 마커 클릭이벤트에 핀 생성 창 올리기
3. [x] 핀을 잇는 dash 선 표현하기
4. [x] 핀의 좌표 얻기
5. [x] 핀의 좌표를 배열에 담아 순서 조작하기

### Labels
- Estimated time: `E: 2h`
- Group : `client`
- Sprint: `Sprint__1`
- Urgency: `High`
