### ISSUE TITLE
[Task] 루트 생성 페이지 마커 상태 관리 리팩토링

### ISSUE THREAD

**Issue by ciocio97** [codestates/MemoryRoad#264]
### ISSUE
- Group:  `client`
- Type: `bug`
- Detail: 지도 위에 마커를 여러개 올렸을 때 생기는 버그를 잡기 위해 리팩토링 진행합니다

### TODO
1. [ ] 빨간 핀 상태 , 파란 마커 상태, 회색 마커 상태 따로 관리하기
2. [ ] 저장 버튼과 동시에 상태 초기화 진행 테스트
3. [ ] 최종적으로 빨간 핀만 남게끔 렌더링

### Labels
- Estimated time: `E: 3h`
- Group : `client`
- Sprint: `Sprint__NUMBER1`
- Urgency: `High`
