### ISSUE TITLE
[Task] 루트 생성 페이지 : 검색창, 핀 저장 모달창 구현

### ISSUE THREAD

**Issue by ciocio97** [codestates/MemoryRoad#31]
### ISSUE
- Group:  `client`
- Type: `feature`
- Detail: 루트 생성페이지의 구성 요소 중 일부인, 검색창과 핀 저장 모달창 구현

### TODO
1. [x] 지도의 핀을 클릭했을 때 뜨는 핀 저장 모달창 HTML, CSS 구현 (카카오 API가 순수 HTML을 요구합니다)
2. [x] 지도에서 원하는 핀을 검색할 수 있는 검색창과 검색 버튼 구현 (카카오 API 최대한 활용) -> 직접 찍는 핀과는 다른 색으로 구현.
3. [x] HTML 문서를 문자열로 변환하여 export 하는 작업

### Labels
- Estimated time: `E: 3h`
- Group : `client`
- Sprint: `Sprint__1`
- Urgency: `High`
