### ISSUE TITLE
[Task] Mypage 구현

### ISSUE THREAD

**Issue by haagmin5382** [codestates/MemoryRoad#43]
### ISSUE
- Group:  `client`
- Type:`feature`
- Detail: Mypage 구현 (기능은 없는 상태)

### TODO
1. [x] html과 css로 Mypage 구현
2. [x] CSS Grid로 구성
3. [x] 반응형 웹페이지로 구현

### Labels
- Estimated time: `E: 2h`
- Group : `client`
- Sprint: `Sprint__1`
- Urgency: `Middle`
