### ISSUE TITLE
[Task] 루트 생성 페이지 : 저장된 핀을 연결해 하나의 루트를 생성하는 기능

### ISSUE THREAD

**Issue by ciocio97** [codestates/MemoryRoad#60]
### ISSUE
- Group:  `client`
- Type: `feature`
- Detail: 루트 생성페이지에 있는 핀 저장 모달창을 클릭했을 때 루트의 요소로 작동하는 모든 기능 구현

### TODO
1. [x] 핀 저장 모달창의 저장 버튼을 누르면 오른쪽의 사이드바로 핀 카드가 추가되는 기능
2. [x] 오른쪽 사이드바는 반응형으로 열고 닫을 수 있게 만들기
3. [x] 오른쪽 사이드바에서 핀 카드의 시간을 늘이고 줄이며 조절할 수 있고, 위치 이동에 따라 핀 카드의 순서를 바꿀 수 있는 기능
4. [x] 지도 상의 핀과 오른쪽 사이드바에 저장된 핀의 개수와 순서가 일치해야합니다.
5. [x] 오른쪽 사이드바에서 루트 저장 버튼을 누르면 사용자의 루트 정보를 담아 서버에 post 요청을 보냅니다.

### Labels
- Estimated time: `E: 6h`
- Group : `client`
- Sprint: `Sprint__1`
- Urgency: `High`
