### ISSUE TITLE
[Task] 유효성검사 구현 

### ISSUE THREAD

**Issue by haagmin5382** [codestates/MemoryRoad#73]
### ISSUE
- Group:  `client`
- Type:  `feature`
- Detail: 회원가입, 회원정보 수정시 입력한 값이 유효한지를 검사하는 유효성검사를 구현 

### TODO
1. [x] 유효성 검사 함수를 작성
2. [x] 유효성 검사에 따라 서버에 입력한 정보를 보내줄지를 결정하는 함수를 작성
3. [x] CSS 디자인 수정

### Labels
- Estimated time: `E: 2.5h`
- Group : `client`
- Sprint: `Sprint__1`
- Urgency: `Middle`
